### ISSUE TITLE
安卓构建报错

### ISSUE THREAD

**Issue by lianjianjie** [OpenFlutter/sona#1]
sona版本0.02;
flutter版本0.10.0
安卓构建时报：
`SonaPlugin.kt: (65, 33): Type inference failed. Expected type mismatch: inferred type is String? but String was expected`

**Comment by JarvanMo** [comment]
flutter太新了。我稍后兼容一下。

**Comment by lianjianjie** [comment]
不懂kt语法，我就把下面的常量直接赋值后可以将就运行了，希望有帮助
<img width="602" alt="20181012203509" src="https://user-images.githubusercontent.com/16377699/46869497-a24cf400-ce5e-11e8-949c-53e776f20d9f.png">

**Comment by JarvanMo** [comment]
@lianjianjie 新版本已上传，问题解决了。可以加入OpenFlutter交流群892398530

**Comment by lianjianjie** [comment]
iOS构建时好像也有问题：
<img width="1036" alt="qq20181013-105827 2x" src="https://user-images.githubusercontent.com/16377699/46900590-1aef9700-ced7-11e8-92e9-b55a1420c802.png">

**Comment by JarvanMo** [comment]
我知道怎么回事了。和fluwx冲突了。最晚周一修复。

**Comment by JarvanMo** [comment]
@lianjianjie 升级一下fluwx和sona。这个问题应该解决了。
