### ISSUE TITLE
deviceToken broken on iOS

### ISSUE THREAD

**Issue by tgarm** [OpenFlutter/sona#10]
使用example项目，发现无法推送到iOS设备。
经调试，发现SonaPlugin.m中的didRegisterForRemoteNotificationsWithDeviceToken函数未被调用。将函数复制到项目的AppDelegate.m后问题解决。

最终添加一行代码解决了此问题：
在SonaPlugin.m第18行添加：
    [registrar addApplicationDelegate:instance];
即可解决此问题。

**Comment by JarvanMo** [comment]
你可以发起PR以修复此问题。

**Comment by JarvanMo** [comment]
随时欢迎PR，我最近有点忙。

**Comment by JarvanMo** [comment]
request merged

**Comment by JarvanMo** [comment]
明天发布新版本。
