### ISSUE TITLE
android端收不到推送

### ISSUE THREAD

**Issue by TomkeyZhang** [OpenFlutter/sona#14]
flutter环境如下:
Flutter 1.5.9-pre.177 • channel master • https://github.com/flutter/flutter.git
Framework • revision 91aa36b7bd (2 days ago) • 2019-05-08 03:03:39 -0400
Engine • revision 436a3c70a9
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 8143450941)

排查下来发现MethodChannel的invokeMethod方法必须在UI线程中执行

`methodChannel?.invokeMethod("onReceiveMessageData", result)`

麻烦确认下

**Comment by JarvanMo** [comment]
Service就是主线程啊。

**Comment by TomkeyZhang** [comment]
IntentService 中的onHandleIntent 是运行在工作线程中的:
 /**
     * This method is invoked on the worker thread with a request to process.
     * Only one Intent is processed at a time, but the processing happens on a
     * worker thread that runs independently from other application logic.
     * So, if this code takes a long time, it will hold up other requests to
     * the same IntentService, but it will not hold up anything else.
     * When all requests have been handled, the IntentService stops itself,
     * so you should not call {@link #stopSelf}.
     *
     * @param intent The value passed to {@link
     *               android.content.Context#startService(Intent)}.
     *               This may be null if the service is being restarted after
     *               its process has gone away; see
     *               {@link android.app.Service#onStartCommand}
     *               for details.
     */
    @WorkerThread
    protected abstract void onHandleIntent(@Nullable Intent intent);

**Comment by JarvanMo** [comment]
恕我无法重现。如果你有解决方法，可以PR。而且Sona只会在stable分支上测试。

**Comment by TomkeyZhang** [comment]
目前stable分支(1.5.4)确实可以，抱歉，打扰了
