### ISSUE TITLE
会出现不影响功能的异常

### ISSUE THREAD

**Issue by ug666** [OpenFlutter/sona#15]
在MAC的手机模拟器启动应用后会出现异常，目前只打包成apk测试没问题，IOS还没证书不能测试不知道有没影响

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method registerGeTui on channel com.jarvanmo/sona)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      register (package:sona/src/sona_iml.dart:28:25)
<asynchronous suspension>
#2      register (package:flutter_app/main.dart:50:3)
#3      main (package:flutter_app/main.dart:38:3)
#4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:199:25)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1500:12)
#9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:190:5)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

**Comment by JarvanMo** [comment]
这个一般都是因为packages get的时候出现了问题，可以试试 flutter clean。和lib本身没关系，因为lib里真的有那个方法。
