### ISSUE TITLE
Android安装失败 自定义权限问题

### ISSUE THREAD

**Issue by CcSimple** [OpenFlutter/sona#2]
**如果有一个app用了sona,  其他app安装会失败.** 
**应该是manifest中自定义权限的名字的原因吧**

`<permission android:protectionLevel="normal" android:name="com.jarvanmo.sona.service.SonaPushService"/>`

Failure[INSTALL_FAILED_DUPLICATE_PERMISSION perm=com.jarvanmo.sona.service.SonaPushService pkg=com.xxx.xxx]

**Comment by JarvanMo** [comment]
这个问题稍后解决。

**Comment by JarvanMo** [comment]
@CcSimple 已升级
