### ISSUE TITLE
关于图标的问题

### ISSUE THREAD

**Issue by ChenArno** [OpenFlutter/sona#7]
请问一下有没有设置推送图片的替换功能

**Comment by JarvanMo** [comment]
图标的话应该是在自己原生app里设置了，flutter暂时层面做不到。把图标手动替换一下。

**Comment by ChenArno** [comment]
是在android>app>src>main>res>mipmap每个文件夹下增加吗，好像没生效

**Comment by JarvanMo** [comment]
是在drawable下面。个推官网有指导我记得

**Comment by ChenArno** [comment]
好的，我看错了，多谢大神
