### ISSUE TITLE
通知栏点击动作

### ISSUE THREAD

**Issue by ChenArno** [OpenFlutter/sona#8]
我将app隐藏到后台，(没有完全被杀死),当我收到消息时，点击通知栏，发现不会打开app页面，但是日志会显示收到消息，请问这是要哪里设置一下的

**Comment by JarvanMo** [comment]
通知栏被点击时会有回调onNotificationMessageClicked。不过暂时还没实现。

**Comment by ChenArno** [comment]
好的，大佬问一下，大概什么可以更新

**Comment by JarvanMo** [comment]
没PR的话，得等年后了

**Comment by ChenArno** [comment]
好的，辛苦大神

**Comment by JarvanMo** [comment]
可以试试0.0.8了。

**Comment by ChenArno** [comment]
更新到0.0.8了，点击还是没反应，需要怎么配置一下吗

**Comment by iusn** [comment]
他只实现了android的点击 iOS的还没实现

**Comment by ChenArno** [comment]
我就是用的安卓，华为手机，你可以用？

**Comment by iusn** [comment]
我做的是iOS
我在iOS里实现了这个
sona.onNotificationMessageClicked.listen(_messageData);
但是iOS里这个方法没有实现 android我还没弄

**Comment by ChenArno** [comment]
> 我做的是iOS
> 我在iOS里实现了这个
> sona.onNotificationMessageClicked.listen(_messageData);
> 但是iOS里这个方法没有实现 android我还没弄

我加了这个方法，安卓还是不行，苹果没测试

**Comment by iusn** [comment]
iOS的还要自己创建一个channel 用来和flutter交互，android的我不会

**Comment by ChenArno** [comment]
> iOS的还要自己创建一个channel 用来和flutter交互，android的我不会

好吧，我看看原生要怎么写

**Comment by JarvanMo** [comment]
@ChenArno @iusn 有两点：
- 通知栏推送仅限于android，ios请用透传。透传消息的通知栏需要自己实现。
- android点击通知栏仅仅是打开app，这点是好用的，至于想跳到某个页面需要自己监听onNotificationMessageClicked。

**Comment by ChenArno** [comment]
> @ChenArno @iusn 有两点：
> 
> * 通知栏推送仅限于android，ios请用透传。透传消息的通知栏需要自己实现。
> * android点击通知栏仅仅是打开app，这点是好用的，至于想跳到某个页面需要自己监听onNotificationMessageClicked。

我这个打不开，点击通知栏没反应

**Comment by JarvanMo** [comment]
@ChenArno 
![image](https://user-images.githubusercontent.com/11608487/52768498-a5ecc380-3068-11e9-800b-076bc5e494cd.png)
已经确认没问题。

**Comment by ChenArno** [comment]
> @ChenArno
> ![image](https://user-images.githubusercontent.com/11608487/52768498-a5ecc380-3068-11e9-800b-076bc5e494cd.png)
> 已经确认没问题。

你这个是用官网的推送是吧，这个是可以的，但是用透传的好像不行

**Comment by JarvanMo** [comment]
透传的通知栏需要自己搞。全部自己搞，包括通知栏，点击动作。你还没分清什么是透传消息，什么是通知推送。sona把透传消息回传给flutter，其他的东西需要用户自己弄。况且我只会以官网为准。

**Comment by ChenArno** [comment]
看了后台服务参数代码，是在后台可以设置的// 透传消息设置，1为强制启动应用，客户端接收到消息后就会立即启动应用；2为等待应用启动
    template.setTransmissionType(2);
